name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with: 
        distribution: 'temurin'
        java-version: '17'

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    # Always try to upload the problems report if it exists (will run even if previous steps fail)
    - name: Upload Gradle Problems Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gradle-problems-report
        path: |
          build/reports/problems/problems-report.html
          app/build/reports/problems/problems-report.html
